# Generated by Django 4.2.5 on 2023-10-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividendos', '0002_remove_dividendo_year_dividendo_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dividendo',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='dividendo',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dividendo',
            name='symbol',
            field=models.CharField(max_length=100),
        ),
    ]
