# Generated by Django 4.2.5 on 2023-10-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dividendos', '0003_dividendomodel_alter_dividendo_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dividendo',
        ),
    ]
